version = 1
disable_existing_loggers = false
[formatters.simple]
class = "colorlog.ColoredFormatter"
format = "%(asctime)s %(name)s:%(lineno)s %(funcName)s [%(log_color)s%(levelname)s%(reset)s]: %(message)s"

[handlers.consoleHandler]
class = "colorlog.StreamHandler"
level = "INFO"
formatter = "simple"
stream = "ext://sys.stdout"

[root]
level = "INFO"
handlers = ["consoleHandler"]
